import classes from './JsonLdCardOther.module.css';

import JsonTopArrow from '../../../assets/json-top-arrow.png';
import JsonBottomArrow from '../../../assets/json-bottom-arrow.png';
import BackArrow from '../../../assets/Group 64.png';

const SchemaDefaultValue = 
    '<script type="application/ld+json">' + '\r\n' + 
    '{' + '\r\n' + 
    '    "@context": "https://schema.org",' + '\r\n' + 
    '    "@type": "FAQPage",' + '\r\n' + 
    '    "mainEntity": []' + '\r\n' + 
    '}' + '\r\n' + 
    '</script><!-- This Json-ld FAQ Schema code generated by' + '\r\n' + 
    'markethinkers.com -->';

function JsonLdCardOther() {
  return (
    <>
        <div className='row position-relative'>
            <div className={classes.jsonLdCodeCardBody}>
                <img className={`img-fluid ${classes.jsonBottomArrow}`} src={JsonBottomArrow} alt='JsonBottomArrow' />
                <div className='d-flex flex-row justify-content-between'>
                    <header>
                        JSON-LD FAQ Schema Code
                    </header>
                </div>
                <hr />
                <textarea defaultValue={SchemaDefaultValue}>
                </textarea>
                <hr />
                <a className={classes.editingButton} href='https://support.google.com/tagmanager/answer/6102821?hl=en'>
                    Why Editing is Necessary for Tag Manager?
                </a>
            </div>
        </div>
        <div className='row d-flex flex-column'>
            <div className={classes.jsonLdCodeCardBodyOther}>
                <img className={`img-fluid ${classes.jsonTopArrow}`} src={JsonTopArrow} alt='JsonTopArrow' />
                <a href='www.google.com' className={classes.backToFAQSchemaGeneratorWrapper}>
                    <img className={`img-fluid ${classes.backArrow}`} src={BackArrow} alt='BackArrow' />
                    <div className={classes.backToFAQSchemaGenerator}>
                    Back to FAQ Schema Generator
                    </div>
                </a>
                <div className='d-flex flex-row justify-content-between'>
                    <header>
                        Google Tag Manager Compitable Code
                    </header>
                    <div className={classes.jsonLdSwitchArea}>
                        <label className={classes.jsonLdSwitch}>
                            <input className={classes.jsonLdSwitchInput} id='spaces' type='checkbox' />
                            <span className={classes.slider}></span>
                        </label>
                        <label>
                            Minify
                        </label>
                    </div>
                </div>
                <hr />
                <textarea defaultValue={SchemaDefaultValue}>
                </textarea>
                <hr />
                <button className={classes.copyFAQSchemaButton} type='button'>
                    Copy FAQ Schema
                </button>
            </div>
        </div>
    </>
  )
}

export default JsonLdCardOther;